export const GREENHOUSE_COMPANIES = [
  { name: 'Stripe', boardToken: 'stripe', website: 'https://stripe.com' },
  { name: 'Airbnb', boardToken: 'airbnb', website: 'https://airbnb.com' },
  { name: 'Coinbase', boardToken: 'coinbase', website: 'https://coinbase.com' },
  { name: 'Databricks', boardToken: 'databricks', website: 'https://databricks.com' },
  { name: 'Dropbox', boardToken: 'dropbox', website: 'https://dropbox.com' },
  { name: 'Figma', boardToken: 'figma', website: 'https://figma.com' },
  { name: 'GitLab', boardToken: 'gitlab', website: 'https://gitlab.com' },
  { name: 'Robinhood', boardToken: 'robinhood', website: 'https://robinhood.com' },
  { name: 'Notion', boardToken: 'notion', website: 'https://notion.so' },
  { name: 'Asana', boardToken: 'asana', website: 'https://asana.com' },
  { name: 'Reddit', boardToken: 'reddit', website: 'https://reddit.com' },
  { name: 'Unity', boardToken: 'unity', website: 'https://unity.com' },
  { name: 'Twilio', boardToken: 'twilio', website: 'https://twilio.com' },
  { name: 'Shopify', boardToken: 'shopify', website: 'https://shopify.com' },
  { name: 'Pinterest', boardToken: 'pinterest', website: 'https://pinterest.com' },
  { name: 'HubSpot', boardToken: 'hubspot', website: 'https://hubspot.com' },
  { name: 'Snowflake', boardToken: 'snowflake', website: 'https://snowflake.com' },
  { name: 'Atlassian', boardToken: 'atlassian', website: 'https://atlassian.com' },
];
